
@main
struct UnicodeGenerator {
    static func main() {
        var result = """
        // This is an autogenerated file, do not edit directly.
        #if SWIFT_STDLIB_ENABLE_UNICODE_DATA

        import Swift\n\n
        """

        wordBreakData: do {
            let baseData = getWordBreakPropertyData(for: "utils/unicode/data/17/WordBreakProperty.txt")

            var idx = 0
            let data = baseData.map { (range, property) in
                idx += 1; return WordBreakEntry(index: idx, range: range, property: property)
            }

            let reorderedData = eytzingerize(data, dummy: .init(index: 0, range: 0...0, property: .extend))

            emit(wordBreakData: reorderedData, into: &result)
        }

        graphemeBreakData: do {
            let baseData = getGraphemeBreakPropertyData(for: "utils/unicode/data/17/GraphemeBreakProperty.txt")

            var data: [GraphemeBreakEntry] = []

            for (range, gbp) in baseData {
                guard range.count < 0x200 else {
                    let _ = String(range.lowerBound, radix: 16)
                    let _ = String(range.upperBound, radix: 16)

                    // Manual range
                    continue
                }

                data.append(.init(index: data.count, range: range, property: gbp))
            }

            let reorderedData = eytzingerize(data, dummy: .init(index: 0, range: 0...0, property: .control))

            emit(graphemeBreakData: reorderedData, into: &result)

            let derivedCoreProperties = readFile("utils/unicode/data/17/DerivedCoreProperties.txt")
            let consonants = getInCB(.consonant, from: derivedCoreProperties)
            emit(inCB: .consonant, consonants, into: &result)
        }

        scriptData: do {
            let scriptData = getScriptData(for: "utils/unicode/data/17/Scripts.txt")
            emit(scriptData: scriptData, into: &result)

            let scriptExtensionData = getScriptExtensionData(for: "utils/unicode/data/17/ScriptExtensions.txt")
            emit(scriptExtensionData: scriptExtensionData, into: &result)
        }

        emojiData: do {
            let emojiData = getEmojiData(for: "utils/unicode/data/17/emoji-data.txt")
            emit(emojiData: emojiData, into: &result)
        }

        caseData: do {
            let caseData = getCaseData(for: "utils/unicode/data/17/CaseFolding.txt")
            emit(caseData: caseData, into: &result)
        }

        normalizationData: do {
            let derivedNormalizationProps = readFile("utils/unicode/data/17/DerivedNormalizationProps.txt")

            let unicodeData = readFile("utils/unicode/data/17/UnicodeData.txt")

            var normData: [UInt32: UInt16] = [:]
            getQCData(from: derivedNormalizationProps, with: &normData)
            getCCCData(from: unicodeData, with: &normData)

            let flattenedNormData = flatten(Array(normData))
            emit(normData: flattenedNormData, into: &result)

            let decompData = getDecompData(from: unicodeData)
            let decompMph = Mph(for: decompData.map { UInt64($0.0) }) // TODO: Try key-path
            emit(decomp: decompMph, decompData, into: &result)

            let compExclusions = getCompExclusions(from: derivedNormalizationProps)
            let filteredDecomp = decompData.filter { (scalar, _) in
                !compExclusions.contains { $0.contains(scalar) }
            }
            // TODO: Interesting...
            let compMph = Mph(for: Array(Set(filteredDecomp.map { UInt64($0.1[1]) })))
            emit(comp: compMph, filteredDecomp, into: &result)
        }

        scalarData: do {

        }

        result += "#endif"

        print(result)
    }
}

extension Bool {
    var not: Self { !self }
}

extension Unicode {
    enum WordBreakProperty: UInt8 {
        case extend
        case format
        case katakana
        case hebrewLetter
        case aLetter
        case midNumLet
        case midLetter
        case midNum
        case numeric
        case extendNumLet
        case wSegSpace

        init?(_ string: borrowing String) {
            guard let value: Self = switch string {
                case "Extend":        .extend
                case "Format":        .format
                case "Katakana":      .katakana
                case "Hebrew_Letter": .hebrewLetter
                case "ALetter":       .aLetter
                case "MidNumLet":     .midNumLet
                case "MidLetter":     .midLetter
                case "MidNum":        .midNum
                case "Numeric":       .numeric
                case "ExtendNumLet":  .extendNumLet
                case "WSegSpace":     .wSegSpace
                case _: nil
            } else { return nil }
            self = value
        }
    }

    enum GraphemeBreakProperty: UInt32 {
        case control
        case extend
        case prepend
        case spacingMark

        init?(_ string: String) {
            guard let value: Self = switch string {
                case "Extend":              .extend
                case "Control", "CR", "LF": .control
                case "Prepend":             .prepend
                case "SpacingMark":         .spacingMark
                case _: nil
            } else {
                return nil
            }
            self = value
        }
    }

    enum IndicConjunctBreakProperty: String {
        case consonant = "Consonant"
        case extend = "Extend"
    }

    /// Character script types.
    ///
    /// Note this includes the "meta" script type "Katakana_Or_Hiragana", which
    /// isn't defined by https://www.unicode.org/Public/UCD/latest/ucd/Scripts.txt,
    /// but is defined by https://www.unicode.org/Public/UCD/latest/ucd/PropertyValueAliases.txt.
    /// We may want to split it out, as it's the only case that is a union of
    /// other script types.
    enum Script: String, Hashable, CaseIterable {
        case adlam                 = "Adlam"
        case ahom                  = "Ahom"
        case anatolianHieroglyphs  = "Anatolian_Hieroglyphs"
        case arabic                = "Arabic"
        case armenian              = "Armenian"
        case avestan               = "Avestan"
        case balinese              = "Balinese"
        case bamum                 = "Bamum"
        case bassaVah              = "Bassa_Vah"
        case batak                 = "Batak"
        case bengali               = "Bengali"
        case beriaErfe             = "Beria_Erfe"
        case bhaiksuki             = "Bhaiksuki"
        case bopomofo              = "Bopomofo"
        case brahmi                = "Brahmi"
        case braille               = "Braille"
        case buginese              = "Buginese"
        case buhid                 = "Buhid"
        case canadianAboriginal    = "Canadian_Aboriginal"
        case carian                = "Carian"
        case caucasianAlbanian     = "Caucasian_Albanian"
        case chakma                = "Chakma"
        case cham                  = "Cham"
        case cherokee              = "Cherokee"
        case chorasmian            = "Chorasmian"
        case common                = "Common"
        case coptic                = "Coptic"
        case cuneiform             = "Cuneiform"
        case cypriot               = "Cypriot"
        case cyrillic              = "Cyrillic"
        case cyproMinoan           = "Cypro_Minoan"
        case deseret               = "Deseret"
        case devanagari            = "Devanagari"
        case divesAkuru            = "Dives_Akuru"
        case dogra                 = "Dogra"
        case duployan              = "Duployan"
        case egyptianHieroglyphs   = "Egyptian_Hieroglyphs"
        case elbasan               = "Elbasan"
        case elymaic               = "Elymaic"
        case ethiopic              = "Ethiopic"
        case garay                 = "Garay"
        case georgian              = "Georgian"
        case glagolitic            = "Glagolitic"
        case gothic                = "Gothic"
        case grantha               = "Grantha"
        case greek                 = "Greek"
        case gujarati              = "Gujarati"
        case gunjalaGondi          = "Gunjala_Gondi"
        case gurmukhi              = "Gurmukhi"
        case gurungKhema           = "Gurung_Khema"
        case han                   = "Han"
        case hangul                = "Hangul"
        case hanifiRohingya        = "Hanifi_Rohingya"
        case hanunoo               = "Hanunoo"
        case hatran                = "Hatran"
        case hebrew                = "Hebrew"
        case hiragana              = "Hiragana"
        case imperialAramaic       = "Imperial_Aramaic"
        case inherited             = "Inherited"
        case inscriptionalPahlavi  = "Inscriptional_Pahlavi"
        case inscriptionalParthian = "Inscriptional_Parthian"
        case javanese              = "Javanese"
        case kaithi                = "Kaithi"
        case kannada               = "Kannada"
        case katakana              = "Katakana"
        case katakanaOrHiragana    = "Katakana_Or_Hiragana"
        case kawi                  = "Kawi"
        case kayahLi               = "Kayah_Li"
        case kharoshthi            = "Kharoshthi"
        case khitanSmallScript     = "Khitan_Small_Script"
        case khmer                 = "Khmer"
        case khojki                = "Khojki"
        case khudawadi             = "Khudawadi"
        case lao                   = "Lao"
        case latin                 = "Latin"
        case lepcha                = "Lepcha"
        case limbu                 = "Limbu"
        case linearA               = "Linear_A"
        case linearB               = "Linear_B"
        case lisu                  = "Lisu"
        case lycian                = "Lycian"
        case lydian                = "Lydian"
        case kiratRai              = "Kirat_Rai"
        case mahajani              = "Mahajani"
        case makasar               = "Makasar"
        case malayalam             = "Malayalam"
        case mandaic               = "Mandaic"
        case manichaean            = "Manichaean"
        case marchen               = "Marchen"
        case masaramGondi          = "Masaram_Gondi"
        case medefaidrin           = "Medefaidrin"
        case meeteiMayek           = "Meetei_Mayek"
        case mendeKikakui          = "Mende_Kikakui"
        case meroiticCursive       = "Meroitic_Cursive"
        case meroiticHieroglyphs   = "Meroitic_Hieroglyphs"
        case miao                  = "Miao"
        case modi                  = "Modi"
        case mongolian             = "Mongolian"
        case mro                   = "Mro"
        case multani               = "Multani"
        case myanmar               = "Myanmar"
        case nabataean             = "Nabataean"
        case nagMundari            = "Nag_Mundari"
        case nandinagari           = "Nandinagari"
        case newa                  = "Newa"
        case newTaiLue             = "New_Tai_Lue"
        case nko                   = "Nko"
        case nushu                 = "Nushu"
        case nyiakengPuachueHmong  = "Nyiakeng_Puachue_Hmong"
        case ogham                 = "Ogham"
        case olChiki               = "Ol_Chiki"
        case oldHungarian          = "Old_Hungarian"
        case oldItalic             = "Old_Italic"
        case oldNorthArabian       = "Old_North_Arabian"
        case oldPermic             = "Old_Permic"
        case oldPersian            = "Old_Persian"
        case oldSogdian            = "Old_Sogdian"
        case oldSouthArabian       = "Old_South_Arabian"
        case oldTurkic             = "Old_Turkic"
        case oldUyghur             = "Old_Uyghur"
        case olOnal                = "Ol_Onal"
        case oriya                 = "Oriya"
        case osage                 = "Osage"
        case osmanya               = "Osmanya"
        case pahawhHmong           = "Pahawh_Hmong"
        case palmyrene             = "Palmyrene"
        case pauCinHau             = "Pau_Cin_Hau"
        case phagsPa               = "Phags_Pa"
        case phoenician            = "Phoenician"
        case psalterPahlavi        = "Psalter_Pahlavi"
        case rejang                = "Rejang"
        case runic                 = "Runic"
        case samaritan             = "Samaritan"
        case saurashtra            = "Saurashtra"
        case sharada               = "Sharada"
        case shavian               = "Shavian"
        case siddham               = "Siddham"
        case sidetic               = "Sidetic"
        case signWriting           = "SignWriting"
        case sinhala               = "Sinhala"
        case sogdian               = "Sogdian"
        case soraSompeng           = "Sora_Sompeng"
        case soyombo               = "Soyombo"
        case sundanese             = "Sundanese"
        case sunuwar               = "Sunuwar"
        case sylotiNagri           = "Syloti_Nagri"
        case syriac                = "Syriac"
        case tagalog               = "Tagalog"
        case tagbanwa              = "Tagbanwa"
        case taiLe                 = "Tai_Le"
        case taiTham               = "Tai_Tham"
        case taiViet               = "Tai_Viet"
        case taiYo                 = "Tai_Yo"
        case takri                 = "Takri"
        case tamil                 = "Tamil"
        case tangsa                = "Tangsa"
        case tangut                = "Tangut"
        case telugu                = "Telugu"
        case thaana                = "Thaana"
        case thai                  = "Thai"
        case tibetan               = "Tibetan"
        case tifinagh              = "Tifinagh"
        case tirhuta               = "Tirhuta"
        case todhri                = "Todhri"
        case tolongSiki            = "Tolong_Siki"
        case toto                  = "Toto"
        case tuluTigalari          = "Tulu_Tigalari"
        case ugaritic              = "Ugaritic"
        case unknown               = "Unknown"
        case vai                   = "Vai"
        case vithkuqi              = "Vithkuqi"
        case wancho                = "Wancho"
        case warangCiti            = "Warang_Citi"
        case yezidi                = "Yezidi"
        case yi                    = "Yi"
        case zanabazarSquare       = "Zanabazar_Square"

        init?(fromAbbreviation abbreviation: String) {
            guard let script: Self = switch abbreviation {
                case "Adlm", "adlam":                 .adlam
                case "Aghb", "caucasianalbanian":     .caucasianAlbanian
                case "Ahom":                          .ahom
                case "Arab", "arabic":                .arabic
                case "Armi", "imperialaramaic":       .imperialAramaic
                case "Armn", "armenian":              .armenian
                case "Avst", "avestan":               .avestan
                case "Bali", "balinese":              .balinese
                case "Bamu", "bamum":                 .bamum
                case "Bass", "bassavah":              .bassaVah
                case "Batk", "batak":                 .batak
                case "Beng", "bengali":               .bengali
                case "Berf", "beriaerfe":             .beriaErfe
                case "Bhks", "bhaiksuki":             .bhaiksuki
                case "Bopo", "bopomofo":              .bopomofo
                case "Brah", "brahmi":                .brahmi
                case "Brai", "braille":               .braille
                case "Bugi", "buginese":              .buginese
                case "Buhd", "buhid":                 .buhid
                case "Cakm", "chakma":                .chakma
                case "Cans", "canadianaboriginal":    .canadianAboriginal
                case "Cari", "carian":                .carian
                case "Cham":                          .cham
                case "Cher", "cherokee":              .cherokee
                case "Chrs", "chorasmian":            .chorasmian
                case "Copt", "coptic", "qaac":        .coptic
                case "Cpmn", "cyprominoan":           .cyproMinoan
                case "Cprt", "cypriot":               .cypriot
                case "Cyrl", "cyrillic":              .cyrillic
                case "Deva", "devanagari":            .devanagari
                case "Diak", "divesakuru":            .divesAkuru
                case "Dogr", "dogra":                 .dogra
                case "Dsrt", "deseret":               .deseret
                case "Dupl", "duployan":              .duployan
                case "Egyp", "egyptianhieroglyphs":   .egyptianHieroglyphs
                case "Elba", "elbasan":               .elbasan
                case "Elym", "elymaic":               .elymaic
                case "Ethi", "ethiopic":              .ethiopic
                case "Gara":                          .garay
                case "Geor", "georgian":              .georgian
                case "Glag", "glagolitic":            .glagolitic
                case "Gong", "gunjalagondi":          .gunjalaGondi
                case "Gonm", "masaramgondi":          .masaramGondi
                case "Goth", "gothic":                .gothic
                case "Gran", "grantha":               .grantha
                case "Grek", "greek":                 .greek
                case "Gujr", "gujarati":              .gujarati
                case "Gukh":                          .gurungKhema
                case "Guru", "gurmukhi":              .gurmukhi
                case "Hang", "hangul":                .hangul
                case "Hani", "han":                   .han
                case "Hano", "hanunoo":               .hanunoo
                case "Hatr", "hatran":                .hatran
                case "Hebr", "hebrew":                .hebrew
                case "Hira", "hiragana":              .hiragana
                case "Hluw", "anatolianhieroglyphs":  .anatolianHieroglyphs
                case "Hmng", "pahawhhmong":           .pahawhHmong
                case "Hmnp", "nyiakengpuachuehmong":  .nyiakengPuachueHmong
                case "Hrkt", "katakanaorhiragana":    .katakanaOrHiragana
                case "Hung", "oldhungarian":          .oldHungarian
                case "Ital", "olditalic":             .oldItalic
                case "Java", "javanese":              .javanese
                case "Kali", "kayahli":               .kayahLi
                case "Kawi":                          .kawi
                case "Kana", "katakana":              .katakana
                case "Khar", "kharoshthi":            .kharoshthi
                case "Khmr", "khmer":                 .khmer
                case "Khoj", "khojki":                .khojki
                case "Kits", "khitansmallscript":     .khitanSmallScript
                case "Knda", "kannada":               .kannada
                case "Krai":                          .kiratRai
                case "Kthi", "kaithi":                .kaithi
                case "Lana", "taitham":               .taiTham
                case "Laoo", "lao":                   .lao
                case "Latn", "latin":                 .latin
                case "Lepc", "lepcha":                .lepcha
                case "Limb", "limbu":                 .limbu
                case "Lina", "lineara":               .linearA
                case "Linb", "linearb":               .linearB
                case "Lisu":                          .lisu
                case "Lyci", "lycian":                .lycian
                case "Lydi", "lydian":                .lydian
                case "Mahj", "mahajani":              .mahajani
                case "Maka", "makasar":               .makasar
                case "Mand", "mandaic":               .mandaic
                case "Mani", "manichaean":            .manichaean
                case "Marc", "marchen":               .marchen
                case "Medf", "medefaidrin":           .medefaidrin
                case "Mend", "mendekikakui":          .mendeKikakui
                case "Merc", "meroiticcursive":       .meroiticCursive
                case "Mero", "meroitichieroglyphs":   .meroiticHieroglyphs
                case "Mlym", "malayalam":             .malayalam
                case "Modi":                          .modi
                case "Mong", "mongolian":             .mongolian
                case "Mroo", "mro":                   .mro
                case "Mtei", "meeteimayek":           .meeteiMayek
                case "Mult", "multani":               .multani
                case "Mymr", "myanmar":               .myanmar
                case "Nagm":                          .nagMundari
                case "Nand", "nandinagari":           .nandinagari
                case "Narb", "oldnortharabian":       .oldNorthArabian
                case "Nbat", "nabataean":             .nabataean
                case "Newa":                          .newa
                case "Nkoo", "nko":                   .nko
                case "Nshu", "nushu":                 .nushu
                case "Ogam", "ogham":                 .ogham
                case "Olck", "olchiki":               .olChiki
                case "Onao":                          .olOnal
                case "Orkh", "oldturkic":             .oldTurkic
                case "Orya", "oriya":                 .oriya
                case "Osge", "osage":                 .osage
                case "Osma", "osmanya":               .osmanya
                case "Ougr", "olduyghur":             .oldUyghur
                case "Palm", "palmyrene":             .palmyrene
                case "Pauc", "paucinhau":             .pauCinHau
                case "Perm", "oldpermic":             .oldPermic
                case "Phag", "phagspa":               .phagsPa
                case "Phli", "inscriptionalpahlavi":  .inscriptionalPahlavi
                case "Phlp", "psalterpahlavi":        .psalterPahlavi
                case "Phnx", "phoenician":            .phoenician
                case "Plrd", "miao":                  .miao
                case "Prti", "inscriptionalparthian": .inscriptionalParthian
                case "Rjng", "rejang":                .rejang
                case "Rohg", "hanifirohingya":        .hanifiRohingya
                case "Runr", "runic":                 .runic
                case "Samr", "samaritan":             .samaritan
                case "Sarb", "oldsoutharabian":       .oldSouthArabian
                case "Saur", "saurashtra":            .saurashtra
                case "Sgnw", "signwriting":           .signWriting
                case "Shaw", "shavian":               .shavian
                case "Shrd", "sharada":               .sharada
                case "Sidd", "siddham":               .siddham
                case "Sidt", "sidetic":               .sidetic
                case "Sind", "khudawadi":             .khudawadi
                case "Sinh", "sinhala":               .sinhala
                case "Sogd", "sogdian":               .sogdian
                case "Sogo", "oldsogdian":            .oldSogdian
                case "Sora", "sorasompeng":           .soraSompeng
                case "Soyo", "soyombo":               .soyombo
                case "Sund", "sundanese":             .sundanese
                case "Sunu":                          .sunuwar
                case "Sylo", "sylotinagri":           .sylotiNagri
                case "Syrc", "syriac":                .syriac
                case "Tagb", "tagbanwa":              .tagbanwa
                case "Takr", "takri":                 .takri
                case "Tale", "taile":                 .taiLe
                case "Talu", "newtailue":             .newTaiLue
                case "Taml", "tamil":                 .tamil
                case "Tang", "tangut":                .tangut
                case "Tavt", "taiviet":               .taiViet
                case "Tayo", "taiyo":                 .taiYo
                case "Telu", "telugu":                .telugu
                case "Tfng", "tifinagh":              .tifinagh
                case "Tglg", "tagalog":               .tagalog
                case "Thaa", "thaana":                .thaana
                case "Thai":                          .thai
                case "Tibt", "tibetan":               .tibetan
                case "Tirh", "tirhuta":               .tirhuta
                case "Tnsa", "tangsa":                .tangsa
                case "Todr":                          .todhri
                case "Tols", "tolongsiki":            .tolongSiki
                case "Toto":                          .toto
                case "Tutg":                          .tuluTigalari
                case "Ugar", "ugaritic":              .ugaritic
                case "Vaii", "vai":                   .vai
                case "Vith", "vithkuqi":              .vithkuqi
                case "Wara", "warangciti":            .warangCiti
                case "Wcho", "wancho":                .wancho
                case "Xpeo", "oldpersian":            .oldPersian
                case "Xsux", "cuneiform":             .cuneiform
                case "Yezi", "yezidi":                .yezidi
                case "Yiii", "yi":                    .yi
                case "Zanb", "zanabazarsquare":       .zanabazarSquare
                case "Zinh", "inherited", "qaai":     .inherited
                case "Zyyy", "common":                .common
                case "Zzzz", "unknown":               .unknown
                case _: nil
            } else {
                return nil
            }
            self = script
        }
    }
}

struct WordBreakEntry: Comparable {
    let index: Int
    let range: ClosedRange<UInt32>
    let property: Unicode.WordBreakProperty

    static func < (lhs: Self, rhs: Self) -> Bool { lhs.index < rhs.index }
}

struct GraphemeBreakEntry: Comparable {
    let index: Int
    let range: ClosedRange<UInt32>
    let property: Unicode.GraphemeBreakProperty

    static func < (lhs: Self, rhs: Self) -> Bool { lhs.index < rhs.index }
}

typealias WordBreakPropertyData     = [(range: ClosedRange<UInt32>, property: Unicode.WordBreakProperty)]
typealias GraphemeBreakPropertyData = [(range: ClosedRange<UInt32>, property: Unicode.GraphemeBreakProperty)]
typealias ScriptData                = [(range: ClosedRange<UInt32>, property: String)]
typealias ScriptExtensionData       = [(range: ClosedRange<UInt32>, property: [String])]
typealias EmojiData                 = [ClosedRange<UInt32>]
typealias CaseData                  = [UInt32: [UInt32]]
typealias DecompData                = [(UInt32, [UInt32])]
typealias CompExclusions            = [ClosedRange<UInt32>]

func getCaseData(for path: String) -> CaseData {
    let data = readFile(path)

    var mappings: CaseData = [:]

    for line in data.split(separator: "\n") {
        // Skip comments
        if line.hasPrefix("#") { continue }

        let components = line.split(separator: ";")

        let status = components[1].filter { !$0.isWhitespace }

        // We only care about Common and Full case mappings.
        guard status == "C" || status == "F" else {
            continue
        }

        let scalar = UInt32(components[0], radix: 16)!

        let mapping = components[2].split(separator: " ").map { UInt32($0, radix: 16)! }

        mappings[scalar] = mapping
    }

    return mappings
}

func getWordBreakPropertyData(for path: String) -> WordBreakPropertyData {
    let data = readFile(path)

    var unflattened: WordBreakPropertyData = []

    for line in data.split(separator: "\n") {
        if line.hasPrefix("#") { continue }

        let components = line.split(separator: ";")

        let splitProperty = components[1].split(separator: "#")
        let filteredProperty = splitProperty[0].filter(\.isWhitespace.not)

        guard let gbp = Unicode.WordBreakProperty(filteredProperty) else { continue }

        let filteredScalars = components[0].filter(\.isWhitespace.not)

        let scalars = if filteredScalars.contains(".") {
            let range = filteredScalars.split(separator: ".")
            then UInt32(range[0], radix: 16)! ... UInt32(range[1], radix: 16)!
        } else {
            let scalar = UInt32(filteredScalars, radix: 16)!
            then scalar...scalar
        }

        unflattened.append((scalars, gbp))
    }

    return flatten(unflattened)
}

func getGraphemeBreakPropertyData(for path: String) -> GraphemeBreakPropertyData {
    let data = readFile(path)

    var unflattened: GraphemeBreakPropertyData = []

    for line in data.split(separator: "\n") {
        if line.hasPrefix("#") { continue }

        // Each line in this file is broken up into two sections:
        // 1: Either the singular scalar or a range of scalars who conform to said
        //    grapheme break property.
        // 2: The grapheme break property that said scalar(s) conform to (with
        //    additional comments noting the character category, name and amount of
        //    scalars the range represents).
        let components = line.split(separator: ";")

        // Get the property first because it may be one we don't care about.
        let splitProperty = components[1].split(separator: "#")
        let filteredProperty = splitProperty[0].filter { !$0.isWhitespace }

        guard let gbp = Unicode.GraphemeBreakProperty(filteredProperty) else {
            continue
        }

        let filteredScalars = components[0].filter { !$0.isWhitespace }

        // If we have . appear, it means we have a legitimate range. Otherwise,
        // it's a singular scalar.
        let scalars = if filteredScalars.contains(".") {
            let range = filteredScalars.split(separator: ".")
            then UInt32(range[0], radix: 16)! ... UInt32(range[1], radix: 16)!
        } else {
            let scalar = UInt32(filteredScalars, radix: 16)!
            then scalar...scalar
        }

        unflattened.append((scalars, gbp))
    }

    return flatten(unflattened)
}

func getScriptData(for path: String) -> ScriptData {
    let data = readFile(path)

    var unflattened: ScriptData = []

    for line in data.split(separator: "\n") {
        if line.hasPrefix("#") { continue }

        // Each line in this file is broken up into two sections:
        // 1: Either the singular scalar or a range of scalars who conform to said
        //    grapheme break property.
        // 2: The script that said scalar(s) conforms to.
        let components = line.split(separator: ";")

        // Get the script first because it may be one we don't care about.
        let splitProperty = components[1].split(separator: "#")
        let filteredProperty = splitProperty[0].filter { !$0.isWhitespace }

        guard Unicode.Script(rawValue: filteredProperty) != nil else {
            fatalError("Please add the following script: \(filteredProperty)")
        }

        let filteredScalars = components[0].filter { !$0.isWhitespace }

        // If we have . appear, it means we have a legitimate range. Otherwise,
        // it's a singular scalar.
        let scalars = if filteredScalars.contains(".") {
            let range = filteredScalars.split(separator: ".")
            then UInt32(range[0], radix: 16)! ... UInt32(range[1], radix: 16)!
        } else {
            let scalar = UInt32(filteredScalars, radix: 16)!
            then scalar...scalar
        }

        unflattened.append((scalars, filteredProperty))
    }

    return flatten(unflattened)
}

func getInCB(_ incb: Unicode.IndicConjunctBreakProperty, from data: String) -> [ClosedRange<UInt32>] {
    var unflattened: [(range: ClosedRange<UInt32>, property: Unicode.IndicConjunctBreakProperty)] = []

    for line in data.split(separator: "\n") {
        // Skip comments
        if line.hasPrefix("#") { continue }

        let components = line.split(separator: ";")

        // Get the property first because it may be one we don't care about.
        let filteredProperty = components[1].filter { !$0.isWhitespace }

        // We only care about 'InCB' properties.
        guard filteredProperty == "InCB" else { continue }

        let splitInCBProperty = components[2].split(separator: "#")
        let filteredInCBProperty = splitInCBProperty[0].filter { !$0.isWhitespace }

        guard filteredInCBProperty == incb.rawValue else { continue }

        let filteredScalars = components[0].filter { !$0.isWhitespace }

        // If we have . appear, it means we have a legitimate range. Otherwise,
        // it's a singular scalar.
        let scalars = if filteredScalars.contains(".") {
            let range = filteredScalars.split(separator: ".")
            then UInt32(range[0], radix: 16)! ... UInt32(range[1], radix: 16)!
        } else {
            let scalar = UInt32(filteredScalars, radix: 16)!
            then scalar...scalar
        }

        unflattened.append((scalars, incb))
    }

    return flatten(unflattened).map { $0.0 }
}

func getScriptExtensionData(for path: String) -> ScriptExtensionData {
    let data = readFile(path)

    var unflattened: ScriptExtensionData = []

    for line in data.split(separator: "\n") {
        // Skip comments
        if line.hasPrefix("#") { continue }

        // Each line in this file is broken up into two sections:
        // 1: Either the singular scalar or a range of scalars who conform to said
        //    grapheme break property.
        // 2: The grapheme break property that said scalar(s) conform to (with
        //    additional comments noting the character category, name and amount of
        //    scalars the range represents).
        let components = line.split(separator: ";")

        // Get the property first because it may be one we don't care about.
        let splitProperty = components[1].split(separator: "#")
        let scripts = splitProperty[0].split(separator: " ").map { String($0) }

        let filteredScalars = components[0].filter { !$0.isWhitespace }

        // If we have . appear, it means we have a legitimate range. Otherwise,
        // it's a singular scalar.
        let scalars = if filteredScalars.contains(".") {
            let range = filteredScalars.split(separator: ".")
            then UInt32(range[0], radix: 16)! ... UInt32(range[1], radix: 16)!
        } else {
            let scalar = UInt32(filteredScalars, radix: 16)!
            then scalar...scalar
        }

        unflattened.append((scalars, scripts))
    }

    return flatten(unflattened)
}

func getEmojiData(for path: String) -> EmojiData {
    let data = readFile(path)

    var unflattened: EmojiData = []

    for line in data.split(separator: "\n") {
        // Skip comments
        if line.hasPrefix("#") { continue }

        // Each line in this file is broken up into two sections:
        // 1: Either the singular scalar or a range of scalars who conform to said
        //    grapheme break property.
        // 2: The grapheme break property that said scalar(s) conform to (with
        //    additional comments noting the character category, name and amount of
        //    scalars the range represents).
        let components = line.split(separator: ";")

        // Get the property first because it may be one we don't care about.
        let splitProperty = components[1].split(separator: "#")
        let filteredProperty = splitProperty[0].filter { !$0.isWhitespace }

        guard filteredProperty == "Extended_Pictographic" else {
            continue
        }

        let filteredScalars = components[0].filter { !$0.isWhitespace }

        // If we have . appear, it means we have a legitimate range. Otherwise,
        // it's a singular scalar.
        let scalars = if filteredScalars.contains(".") {
            let range = filteredScalars.split(separator: ".")
            then UInt32(range[0], radix: 16)! ... UInt32(range[1], radix: 16)!
        } else {
            let scalar = UInt32(filteredScalars, radix: 16)!
            then scalar...scalar
        }

        unflattened.append(scalars)
    }

    return flatten(unflattened)
}

// Given a string to the UnicodeData file, return the flattened list of scalar
// to Canonical Decompositions.
//
// Each line in this data file is formatted like the following:
//
//     1B06;BALINESE LETTER AKARA TEDUNG;Lo;0;L;1B05 1B35;;;;N;;;;;
//
// Where each section is split by a ';'. The first section informs us of the
// scalar in the line with the various properties. For the purposes of
// decomposition data, we only need the 1B05 1B35 after the L (index 5) which is
// the array of scalars that the scalars decomposes to.
func getDecompData(from data: String) -> DecompData {
    var unflattened: DecompData = []

    for line in data.split(separator: "\n") {
        let components = line.split(separator: ";", omittingEmptySubsequences: false)

        let decomp = components[5]

        // We either 1. don't have decompositions, or 2. the decompositions is for
        // compatible forms. We only care about NFD, so ignore these cases.
        if decomp == "" || decomp.hasPrefix("<") {
            continue
        }

        let decomposedScalars = decomp.split(separator: " ").map {
            UInt32($0, radix: 16)!
        }

        let scalarStr = components[0]
        let scalar = UInt32(scalarStr, radix: 16)!

        unflattened.append((scalar, decomposedScalars))
    }

    return unflattened
}

func getCompExclusions(from data: String) -> CompExclusions {
    var result: CompExclusions = []

    for line in data.split(separator: "\n") {
        // Skip comments
        if line.hasPrefix("#") { continue }

        let info = line.split(separator: "#")
        let components = info[0].split(separator: ";")

        // Get the property first because we only care about Full_Composition_Exclusion
        let filteredProperty = components[1].filter { !$0.isWhitespace }

        guard filteredProperty == "Full_Composition_Exclusion" else { continue }

        let filteredScalars = components[0].filter { !$0.isWhitespace }

        // If we have . appear, it means we have a legitimate range. Otherwise,
        // it's a singular scalar.
        let scalars = if filteredScalars.contains(".") {
            let range = filteredScalars.split(separator: ".")
            then UInt32(range[0], radix: 16)! ... UInt32(range[1], radix: 16)!
        } else {
            let scalar = UInt32(filteredScalars, radix: 16)!
            then scalar...scalar
        }

        result.append(scalars)
    }

    return result
}

func emit(caseData data: CaseData, into result: inout String) {
    let caseMph = Mph(for: data.keys.map(UInt64.init))

    emitMph(
        caseMph,
        name: "Case",
        label: "CaseFold",
        into: &result
    )

    var caseData: [(UInt32, [UInt32])] = .init(
        repeating: (0, []),
        count: data.keys.count
    )

    for (key, mapping) in data {
        let idx = caseMph.index(for: UInt64(key))
        caseData[idx] = (key, mapping)
    }

    emitCollection(
        caseData,
        name: "unicodeCase",
        type: "UInt64",
        into: &result
    ) {
        // Our original scalar goes at the bottom 21 bits.
        var value = UInt64($0)

        // If our scalar is a Full mapping (maps to more than 1 scalar), then
        // set the top bit to indicate another look through and move on.
        guard $1.count == 1 else {
            value |= 0x1 << 63
            return "0x\(String(value, radix: 16, uppercase: true))"
        }

        let distance = Int32($0) - Int32($1[0])

        value |= UInt64(UInt32(bitPattern: distance)) << 21

        return "0x\(String(value, radix: 16, uppercase: true))"
    }

    let fullData = data.filter { $1.count > 1 }
    let fullMph = Mph(for: fullData.keys.map { UInt64($0) })

    emitMph(
        fullMph,
        name: "CaseFull",
        label: "CaseFullFold",
        into: &result
    )

    var fullCaseData: [(UInt32, [UInt32])] = .init(
        repeating: (0, []),
        count: fullData.count
    )

    for (key, mapping) in fullData {
        let idx = fullMph.index(for: UInt64(key))
        fullCaseData[idx] = (key, mapping)
    }

    emitCollection(
        fullCaseData,
        name: "unicodeCaseFull",
        type: "UInt64",
        into: &result
    ) {
        var value: UInt64 = 0

        // Store the count in the top 2 bits.
        precondition((2...3).contains($1.count))
        value |= UInt64($1.count) << 62

        for (i, scalar) in $1.enumerated() {
            let distance = Int32($0) - Int32(scalar)
            precondition(distance.magnitude <= UInt16.max)

            value |= UInt64(distance.magnitude) << (i * 17)

            if distance < 0 { value |= 0x10000 << (i * 17) }
        }

        return "0x\(String(value, radix: 16, uppercase: true))"
    }
}

func emit(wordBreakData data: [WordBreakEntry], into result: inout String) {
    emitCollection(
        data,
        name: "unicodeWords",
        type: "UInt32",
        into: &result
    ) {
        "0x\(String($0.range.lowerBound | (UInt32($0.range.count) << 21), radix: 16, uppercase: true))"
    }

    emitCollection(
        data,
        name: "unicodeWordsData",
        type: "UInt8",
        into: &result
    ) {
        "0x\(String($0.property.rawValue, radix: 16, uppercase: true))"
    }
}

func emit(graphemeBreakData data: [GraphemeBreakEntry], into result: inout String) {
    result += "let unicodeGraphemeBreakProperties: InlineArray<\(data.count), UInt32> = [\n"

    formatCollection(data, into: &result) { entry in
        let range = entry.range
        let gbp = entry.property

        // Our value uses the 21 bits to represent the scalar, 8 bits to represent
        // the range's count, and finally the last three bits to represent the
        // grapheme break property enum.

        // E.g. for the top 3 bits:
        // 000 = control
        // 001 = extend
        // 010 = prepend
        // 011 = spacingMark
        // 100 = not used (will never occur)
        // 101 = not used (will never occur)
        // 110 = not used (will never occur)
        // 111 = not used (will never occur)
        var value = range.lowerBound
        value |= UInt32(range.count - 1) << 21
        value |= gbp.rawValue << 29

        return "0x\(String(value, radix: 16, uppercase: true))"
    }

    result += "\n]\n\n"
}

func emit(inCB incb: Unicode.IndicConjunctBreakProperty, _ data: [ClosedRange<UInt32>], into result: inout String) {
    // 64 bit arrays * 8 bytes = .512 KB
    var bitArrays: [BitArray] = .init(repeating: .init(size: 64), count: 64)

    let chunkSize = 0x110000 / 64 / 64

    var chunks: [Int] = []

    for i in 0 ..< 64 * 64 {
        let lower = i * chunkSize
        let upper = lower + chunkSize - 1

        let idx = i / 64
        let bit = i % 64

        for scalar in lower ... upper {
            if data.contains(where: { $0.contains(UInt32(scalar)) }) {
                chunks.append(i)

                bitArrays[idx][bit] = true
                break
            }
        }
    }

    // Remove the trailing 0s. Currently this reduces quick look size down to
    // 96 bytes from 512 bytes.
    var reducedBA = Array(bitArrays.reversed())
    reducedBA = Array(reducedBA.drop { $0.words == [0x0] })

    bitArrays = reducedBA.reversed()

    // Keep a record of every rank for all the bitarrays.
    var ranks: [UInt16] = []

    // Record our quick look ranks.
    var lastRank: UInt16 = 0
    for (i, _) in bitArrays.enumerated() {
        guard i != 0 else {
            ranks.append(0)
            continue
        }

        var rank = UInt16(bitArrays[i - 1].words[0].nonzeroBitCount)
        rank += lastRank

        ranks.append(rank)

        lastRank = rank
    }

    // Insert our quick look size at the beginning.
    var size = BitArray(size: 64)
    size.words = [UInt64(bitArrays.count)]
    bitArrays.insert(size, at: 0)

    for chunk in chunks {
        var chunkBA = BitArray(size: chunkSize)

        let lower = chunk * chunkSize
        let upper = lower + chunkSize

        for scalar in lower ..< upper {
            if data.contains(where: { $0.contains(UInt32(scalar)) }) {
                chunkBA[scalar % chunkSize] = true
            }
        }

        // Append our chunk bit array's rank.
        var lastRank: UInt16 = 0
        for (i, _) in chunkBA.words.enumerated() {
            guard i != 0 else {
                ranks.append(0)
                continue
            }

            var rank = UInt16(chunkBA.words[i - 1].nonzeroBitCount)
            rank += lastRank

            ranks.append(rank)
            lastRank = rank
        }

        bitArrays += chunkBA.words.map {
            var ba = BitArray(size: 64)
            ba.words = [$0]
            return ba
        }
    }

    emitCollection(
        ranks,
        name: "unicodeInCB\(incb.rawValue)Ranks",
        into: &result
    )

    emitCollection(
        bitArrays,
        name: "unicodeInCB\(incb.rawValue)",
        type: "UInt64",
        into: &result
    ) {
        precondition($0.words.count == 1)
        return "0x\(String($0.words[0], radix: 16, uppercase: true))"
    }
}

func emit(scriptData data: ScriptData, into result: inout String) {
    var scriptData: [UInt32: Unicode.Script] = [:]

    for (range, property) in data {
        for scalar in range {
            scriptData[scalar] = Unicode.Script(rawValue: property)
        }
    }

    for i in 0x0...0x10FFFF {
        guard let scalar = Unicode.Scalar(i) else { continue }

        if !scriptData.keys.contains(scalar.value) {
            scriptData[scalar.value] = .unknown
        }
    }

    let data = flatten(Array(scriptData))

    emitCollection(
        data,
        name: "unicodeScripts",
        type: "UInt32",
        into: &result
    ) {
        var value = $0.0.lowerBound // TODO: This is unreadable.
        value |= UInt32(unsafeBitCast($0.1, to: UInt8.self)) << 21

        return "0x\(String(value, radix: 16, uppercase: true))"
    }
}

func emit(scriptExtensionData data: ScriptExtensionData, into result: inout String) {
    var indices: [[String]: UInt16] = [:]
    var bytes: [UInt8] = []
    var currentIndex: UInt16 = 0

    for (_, scripts) in data {
        if indices.keys.contains(scripts) { continue }

        indices[scripts] = currentIndex | (UInt16(scripts.count) << 11)

        for script in scripts {
            let scriptEnum = Unicode.Script(fromAbbreviation: script)!
            let byte = unsafeBitCast(scriptEnum, to: UInt8.self)

            bytes.append(byte)
            currentIndex += 1
        }
    }

    // 64 bit arrays * 8 bytes = .512 KB
    var bitArrays: [BitArray] = .init(repeating: .init(size: 64), count: 64)

    let chunkSize = 0x110000 / 64 / 64

    var chunks: [Int] = []

    for i in 0 ..< 64 * 64 {
        let lower = i * chunkSize
        let upper = lower + chunkSize - 1

        let idx = i / 64
        let bit = i % 64

        for scalar in lower ... upper {
            if data.contains(where: { $0.0.contains(UInt32(scalar)) }) {
                chunks.append(i)

                bitArrays[idx][bit] = true
                break
            }
        }
    }

    // Remove the trailing 0s. Currently this reduces quick look size down to
    // 96 bytes from 512 bytes.
    var reducedBA = Array(bitArrays.reversed())
    reducedBA = Array(reducedBA.drop {
        $0.words == [0x0]
    })

    bitArrays = reducedBA.reversed()

    // Keep a record of every rank for all the bitarrays.
    var ranks: [UInt16] = []

    // Record our quick look ranks.
    var lastRank: UInt16 = 0
    for (i, _) in bitArrays.enumerated() {
        guard i != 0 else {
            ranks.append(0)
            continue
        }

        var rank = UInt16(bitArrays[i - 1].words[0].nonzeroBitCount)
        rank += lastRank

        ranks.append(rank)

        lastRank = rank
    }

    // Insert our quick look size at the beginning.
    var size = BitArray(size: 64)
    size.words = [UInt64(bitArrays.count)]
    bitArrays.insert(size, at: 0)

    var dataIndices: [UInt16] = []

    for chunk in chunks {
        var chunkBA = BitArray(size: chunkSize)

        let lower = chunk * chunkSize
        let upper = lower + chunkSize

        let chunkDataIdx = UInt64(dataIndices.endIndex)

        // Insert our chunk's data index in the upper bits of the last word of our
        // bit array.
        chunkBA.words[chunkBA.words.endIndex - 1] |= chunkDataIdx << 16

        for scalar in lower ..< upper {
            if data.contains(where: { $0.0.contains(UInt32(scalar)) }) {
                chunkBA[scalar % chunkSize] = true

                let data = data[data.firstIndex {
                    $0.0.contains(UInt32(scalar))
                }!].1

                dataIndices.append(indices[data]!)
            }
        }

        // Append our chunk bit array's rank.
        var lastRank: UInt16 = 0
        for (i, _) in chunkBA.words.enumerated() {
            guard i != 0 else {
                ranks.append(0)
                continue
            }

            var rank = UInt16(chunkBA.words[i - 1].nonzeroBitCount)
            rank += lastRank

            ranks.append(rank)
            lastRank = rank
        }

        bitArrays += chunkBA.words.map {
            var ba = BitArray(size: 64)
            ba.words = [$0]
            return ba
        }
    }

    emitCollection(
        bytes,
        name: "unicodeScriptExtensionsData",
        into: &result
    )

    emitCollection(
        dataIndices,
        name: "unicodeScriptExtensionsDataIndices",
        into: &result
    )

    emitCollection(
        ranks,
        name: "unicodeScriptExtensionsRanks",
        into: &result
    )

    emitCollection(
        bitArrays,
        name: "unicodeScriptExtensions",
        type: "UInt64",
        into: &result
    ) {
        precondition($0.words.count == 1)
        return "0x\(String($0.words[0], radix: 16, uppercase: true))"
    }
}

func emit(emojiData data: EmojiData, into result: inout String) {
    // 64 bit arrays * 8 bytes = .512 KB
    var bitArrays: [BitArray] = .init(repeating: .init(size: 64), count: 64)

    let chunkSize = 0x110000 / 64 / 64

    var chunks: [Int] = []

    for i in 0 ..< 64 * 64 {
        let lower = i * chunkSize
        let upper = lower + chunkSize - 1

        let idx = i / 64
        let bit = i % 64

        for scalar in lower ... upper {
            if data.contains(where: { $0.contains(UInt32(scalar)) }) {
                chunks.append(i)

                bitArrays[idx][bit] = true
                break
            }
        }
    }

    // Remove the trailing 0s. Currently this reduces quick look size down to
    // 96 bytes from 512 bytes.
    var reducedBA = Array(bitArrays.reversed())
    reducedBA = Array(reducedBA.drop { $0.words == [0x0] })

    bitArrays = reducedBA.reversed()

    // Keep a record of every rank for all the bitarrays.
    var ranks: [UInt16] = []

    // Record our quick look ranks.
    var lastRank: UInt16 = 0
    for (i, _) in bitArrays.enumerated() {
        guard i != 0 else {
            ranks.append(0)
            continue
        }

        var rank = UInt16(bitArrays[i - 1].words[0].nonzeroBitCount)
        rank += lastRank

        ranks.append(rank)

        lastRank = rank
    }

    // Insert our quick look size at the beginning.
    var size = BitArray(size: 64)
    size.words = [UInt64(bitArrays.count)]
    bitArrays.insert(size, at: 0)

    for chunk in chunks {
        var chunkBA = BitArray(size: chunkSize)

        let lower = chunk * chunkSize
        let upper = lower + chunkSize

        for scalar in lower ..< upper {
            if data.contains(where: { $0.contains(UInt32(scalar)) }) {
                chunkBA[scalar % chunkSize] = true
            }
        }

        // Append our chunk bit array's rank.
        var lastRank: UInt16 = 0
        for (i, _) in chunkBA.words.enumerated() {
            guard i != 0 else {
                ranks.append(0)
                continue
            }

            var rank = UInt16(chunkBA.words[i - 1].nonzeroBitCount)
            rank += lastRank

            ranks.append(rank)
            lastRank = rank
        }

        bitArrays += chunkBA.words.map {
            var ba = BitArray(size: 64)
            ba.words = [$0]
            return ba
        }
    }

    emitCollection(
        ranks,
        name: "unicodeEmojiDataRanks",
        into: &result
    )

    emitCollection(
        bitArrays,
        name: "unicodeEmojiData",
        type: "UInt64",
        into: &result
    ) {
        precondition($0.words.count == 1)
        return "0x\(String($0.words[0], radix: 16, uppercase: true))"
    }
}

func emit(normData data: [(ClosedRange<UInt32>, UInt16)], into result: inout String) {
    let uniqueData = Array(Set(data.map { $0.1 }))

    // 64 bit arrays * 8 bytes = .512 KB
    var bitArrays: [BitArray] = .init(repeating: .init(size: 64), count: 64)

    let chunkSize = 0x110000 / 64 / 64

    var chunks: [Int] = []

    for i in 0 ..< 64 * 64 {
        let lower = i * chunkSize
        let upper = lower + chunkSize - 1

        let idx = i / 64
        let bit = i % 64

        for scalar in lower...upper {
            if data.contains(where: { $0.0.contains(UInt32(scalar)) }) {
                chunks.append(i)

                bitArrays[idx][bit] = true
                break
            }
        }
    }

    // Remove the trailing 0s. Currently this reduces quick look size down to
    // 96 bytes from 512 bytes.
    var reducedBA = Array(bitArrays.reversed())
    reducedBA = Array(reducedBA.drop { $0.words == [0x0] })

    bitArrays = reducedBA.reversed()

    // Keep a record of every rank for all the bitarrays.
    var ranks: [UInt16] = []

    // Record our quick look ranks.
    var lastRank: UInt16 = 0
    for (i, _) in bitArrays.enumerated() {
        guard i != 0 else {
            ranks.append(0)
            continue
        }

        var rank = UInt16(bitArrays[i - 1].words[0].nonzeroBitCount)
        rank += lastRank

        ranks.append(rank)

        lastRank = rank
    }

    // Insert our quick look size at the beginning.
    var size = BitArray(size: 64)
    size.words = [UInt64(bitArrays.count)]
    bitArrays.insert(size, at: 0)

    var dataIndices: [UInt8] = []

    for chunk in chunks {
        var chunkBA = BitArray(size: chunkSize)

        let lower = chunk * chunkSize
        let upper = lower + chunkSize

        let chunkDataIdx = UInt64(dataIndices.endIndex)

        // Insert our chunk's data index in the upper bits of the last word of our
        // bit array.
        chunkBA.words[chunkBA.words.endIndex - 1] |= chunkDataIdx << 16

        for scalar in lower ..< upper where data.contains(where: { $0.0.contains(UInt32(scalar)) }) {
            chunkBA[scalar % chunkSize] = true

            let data = data[data.firstIndex { $0.0.contains(UInt32(scalar)) }!].1
            let dataIdx = uniqueData.firstIndex(of: data)!

            dataIndices.append(UInt8(dataIdx))
        }

        // Append our chunk bit array's rank.
        var lastRank: UInt16 = 0
        for (i, _) in chunkBA.words.enumerated() {
            guard i != 0 else {
                ranks.append(0)
                continue
            }

            var rank = UInt16(chunkBA.words[i - 1].nonzeroBitCount)
            rank += lastRank

            ranks.append(rank)
            lastRank = rank
        }

        bitArrays += chunkBA.words.map {
            var ba = BitArray(size: 64)
            ba.words = [$0]
            return ba
        }
    }

    emitCollection(
        uniqueData,
        name: "unicodeNormDataData",
        into: &result
    )

    emitCollection(
        dataIndices,
        name: "unicodeNormDataDataIndices",
        into: &result
    )

    emitCollection(
        ranks,
        name: "unicodeNormDataRanks",
        into: &result
    )

    emitCollection(
        bitArrays,
        name: "unicodeNormData",
        type: "UInt64",
        into: &result
    ) {
        precondition($0.words.count == 1)
        return "0x\(String($0.words[0], radix: 16, uppercase: true))"
    }
}

// Takes a mph for the keys and the data values and writes the required data into arrays.
func emit(decomp mph: Mph, _ data: [(UInt32, [UInt32])], into result: inout String) {
    emitMph(
        mph,
        name: "NfdDecomp",
        label: "NfdDecomp",
        into: &result
    )

    // Fixup the decomposed scalars first for full decompositions.

    var data = data

    func decompose(_ scalar: UInt32, into result: inout [UInt32]) {
        if scalar <= 0x7F {
            result.append(scalar)
            return
        }

        if let decomp = data.first(where: { $0.0 == scalar }) {
            for scalar in decomp.1 {
                decompose(scalar, into: &result)
            }
        } else {
            result.append(scalar)
        }
    }

    for (i, (_, rawDecomposed)) in data.enumerated() {
        var newDecomposed: [UInt32] = []

        for rawScalar in rawDecomposed {
            decompose(rawScalar, into: &newDecomposed)
        }

        data[i].1 = newDecomposed
    }

    var sortedData: [(UInt32, UInt16)] = []

    for (scalar, _) in data {
        sortedData.append((scalar, UInt16(mph.index(for: UInt64(scalar)))))
    }

    sortedData.sort { $0.1 < $1.1 }

    let indices = emit(decompDecomp: data, sortedData, into: &result)
    emit(decompIndices: indices, into: &result)
}

func emit(
    decompDecomp data: [(UInt32, [UInt32])],
    _ sortedData: [(UInt32, UInt16)],
    into result: inout String
) -> [(UInt32, UInt16)] {
    var indices: [(UInt32, UInt16)] = []
    var decompResult: [UInt8] = []

    // Keep a record of decompositions because some scalars share the same
    // decomposition, so instead of emitting it twice, both scalars just point at
    // the same decomposition index.
    var uniqueDecomps: [[UInt32]: UInt16] = [:]

    for (scalar, _) in sortedData {
        let decomp = data.first(where: { $0.0 == scalar })!.1

        // If we've seen this decomp before, use it.
        if let idx = uniqueDecomps[decomp] {
        indices.append((scalar, idx))
        continue
        }

        indices.append((scalar, UInt16(decompResult.count)))

        // This is our NFD decomposition utf8 string count.
        decompResult.append(0)
        let sizeIdx = decompResult.count - 1

        uniqueDecomps[decomp] = UInt16(sizeIdx)

        for scalar in decomp {
            let realScalar = Unicode.Scalar(scalar)!
            decompResult[sizeIdx] += UInt8(realScalar.utf8.count)
            for utf8 in realScalar.utf8 { decompResult.append(utf8) }
        }
    }

    result += "let unicodeNfdDecomp: InlineArray<\(decompResult.count), UInt8> = [\n"

    formatCollection(decompResult, into: &result) { value -> String in
        return "0x\(String(value, radix: 16, uppercase: true))"
    }

    result += "\n]\n\n"

    return indices
}

func emit(decompIndices indices: [(UInt32, UInt16)], into result: inout String) {
    result += "let unicodeNfdDecompIndices: InlineArray<\(indices.count), UInt32> = [\n"

    formatCollection(indices, into: &result) { (scalar, idx) -> String in
        // Make sure that these scalars don't exceed past 18 bits. We need the other
        // 14 bits to store the index into decomp array. Although Unicode scalars
        // can go up to 21 bits, none of the higher scalars actually decompose into
        // anything or aren't assigned yet.
        precondition(scalar <= 0x3FFFF)
        var value = scalar
        value |= UInt32(idx) << 18

        return "0x\(String(value, radix: 16, uppercase: true))"
    }

    result += "\n]\n\n"
}

func emit(comp mph: Mph, _ data: [(UInt32, [UInt32])], into result: inout String) {
    emitMph(
        mph,
        name: "NfcComp",
        label: "NfcComp",
        into: &result
    )

    emit(compComps: mph, data, into: &result)
}

func emit(compComps mph: Mph, _ data: [(UInt32, [UInt32])], into result: inout String) {
    let uniqueKeys = Set(data.map { $0.1[1] })
    var sortedData: [[(UInt32, UInt32)]] = .init(
        repeating: [],
        count: uniqueKeys.count
    )

    for (scalar, comp) in data {
        let idx = mph.index(for: UInt64(comp[1]))
        if sortedData[idx].isEmpty { sortedData[idx].append((comp[1], .max)) }
        sortedData[idx].append((comp[0], scalar))
    }

    // Initialize our flat data and offsets arrays
    var flattenedCompValues: [String] = []
    var compOffsets: [UInt16] = [0]

    for compList in sortedData {
        // Collect the formatted hex strings for this specific composition list
        var formattedList: [String] = []

        for (comp, scalar) in compList {
            let hexString = if scalar == .max {
                // This only occurs for the first element who stores the original y scalar
                // in the composition and the size of the array.
                "0x\(String(comp, radix: 16, uppercase: true))"
            } else {
                // Make sure that these scalars don't exceed past 17 bits. We need the other
                // 15 bits to store the range to the final composition. Although Unicode
                // scalars can go up to 21 bits, none of the compositions with this scalar
                // go that high.
                precondition(comp <= 0x1FFFF)
                var value = comp

                // Calculate the distance from our current composition scalar to our final
                // composed scalar.
                let distance = Int(scalar) - Int(comp)
                // Make sure that our distance doesn't exceed 14 bits. Although the above
                // assertion gives us 15 bits, we use the last bit to indicate negative
                // or not.
                precondition(distance <= 0x3FFF)

                value |= UInt32(distance.magnitude) << 17

                if distance < 0 { value |= 1 << 31 }

                then "0x\(String(value, radix: 16, uppercase: true))"
            }

            formattedList.append(hexString)
        }

        flattenedCompValues.append(contentsOf: formattedList)
        compOffsets.append(UInt16(flattenedCompValues.count))
    }

    emitCollection(
        flattenedCompValues,
        name: "unicodeNfcCompData",
        type: "UInt32",
        into: &result,
        formatter: \.self
    )

    emitCollection(
        compOffsets,
        name: "unicodeNfcCompDataOffsets",
        into: &result
    )
}
